### ISSUE TITLE
Variables don't exist after container image is updated

### ISSUE THREAD

**Issue by punkstar** [meanbee/docker-magento-mysql#1]
When trying to run a Magento import from the admin interface we got the error:

    SQLSTATE[42S02]: Base table or view not found: 1146 Table 'performance_schema.session_variables' doesn't exist, query was: SHOW VARIABLES LIKE "max_allowed_packet"

When logging into the container and running `SHOW VARIABLES` we'd get the same error.  This was fixed by explicitly running `mysql_upgrade` within the container to bring the data in line with the new MySQL server version.

https://stackoverflow.com/questions/31967527/table-performance-schema-session-variables-doesnt-exist

**Comment by bobbyshaw** [comment]
Closing as this repo is no longer maintained and will be marked as read-only.
